import { RequestData, RequestTimeZone, RequestType } from "../types/types"

export const requestData: RequestData = {
  data: [
    {
			name: 'Emma Smith',
      requestTimeZone: RequestTimeZone.US_PST,
      signupDate: "1/2/2020",
      requestType: RequestType.PHONE,
      investmentDate: "1/2/2021",
      investmentTime: "06:00",
      refundRequestDate: "1/2/2021",
      refundRequestTime: "09:00",
    },
    {
			name: 'Benjamin Johnson',
      requestTimeZone: RequestTimeZone.EUROPE_CET,
      signupDate: "12/2/2020",
      requestType: RequestType.WEB_APP,
      investmentDate: "2/1/2021",
      investmentTime: "06:30",
      refundRequestDate: "1/2/2021",
      refundRequestTime: "23:00",
    },
    {
			name: 'Olivia Davis',
      requestTimeZone: RequestTimeZone.EUROPE_CET,
      signupDate: "1/2/2020",
      requestType: RequestType.WEB_APP,
      investmentDate: "2/2/2021",
      investmentTime: "13:00",
      refundRequestDate: "2/2/2021",
      refundRequestTime: "20:00",
    },
    {
			name: 'Ethan Anderson',
      requestTimeZone: RequestTimeZone.US_PST,
      signupDate: "1/11/2011",
      requestType: RequestType.WEB_APP,
      investmentDate: "2/1/2021",
      investmentTime: "13:00",
      refundRequestDate: "2/2/2021",
      refundRequestTime: "16:00",
    },
    {
			name: 'Sophia Wilson',
      requestTimeZone: RequestTimeZone.US_PST,
      signupDate: "2/1/2020",
      requestType: RequestType.PHONE,
      investmentDate: "2/1/2021",
      investmentTime: "22:00",
      refundRequestDate: "2/2/2021",
      refundRequestTime: "05:00",
    },
    {
			name: 'Liam Martinez',
      requestTimeZone: RequestTimeZone.EUROPE_GMT,
      signupDate: "1/1/2020",
      requestType: RequestType.WEB_APP,
      investmentDate: "1/1/2021",
      investmentTime: "11:00",
      refundRequestDate: "11/1/2021",
      refundRequestTime: "12:00",
    },
    {
			name: 'Jonathan Giles',
      requestTimeZone: RequestTimeZone.EUROPE_CET,
      signupDate: "1/1/2020",
      requestType: RequestType.PHONE,
      investmentDate: "1/1/2021",
      investmentTime: "11:00",
      refundRequestDate: "12/1/2021",
      refundRequestTime: "12:00",
    },
    {
			name: 'Priya Sharp',
      requestTimeZone: RequestTimeZone.EUROPE_CET,
      signupDate: "10/10/2020",
      requestType: RequestType.PHONE,
      investmentDate: "5/5/2021",
      investmentTime: "00:30",
      refundRequestDate: "5/5/2021",
      refundRequestTime: "21:00",
    },
    {
			name: 'Raja Ortiz',
      requestTimeZone: RequestTimeZone.US_EST,
      signupDate: "10/10/2021",
      requestType: RequestType.PHONE,
      investmentDate: "01/15/2022",
      investmentTime: "21:30",
      refundRequestDate: "01/16/2022",
      refundRequestTime: "07:00",
    },
    {
			name: 'Livia Burns',
      requestTimeZone: RequestTimeZone.US_PST,
      signupDate: "10/10/2021",
      requestType: RequestType.PHONE,
      investmentDate: "01/15/2022",
      investmentTime: "21:30",
      refundRequestDate: "01/16/2022",
      refundRequestTime: "19:00",
    },
    {
			name: 'Lacey Gates',
      requestTimeZone: RequestTimeZone.EUROPE_CET,
      signupDate: "10/10/2021",
      requestType: RequestType.WEB_APP,
      investmentDate: "15/01/2022",
      investmentTime: "23:36",
      refundRequestDate: "16/01/2022",
      refundRequestTime: "13:12",
    },
  ],
}
